language: java

services:
  - mysql

before_install:
  - mysql -u root --password="" < sql/imhungry.sql

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root1234!') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
