language: java

services:
  - mysql

before_install:
  - mysql -u root --password="" < src/test/imhungry.sqltest

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
